pull_request_rules:
  - name: automatic approval for depfu pull requests
    conditions:
      - author=depfu[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving depfu

  - name: Automatic merge for Depfu minor and patch pull requests
    conditions:
      - base=main
      - label=depfu
      - files~=package(-lock)?.json$
      - "#files=2"
      - author=depfu[bot]
      - title~=(\(minor\)|\(patch\))$
    actions:
      merge:
        method: merge
