# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-code:
    name: Validate code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run format:check
      - run: npm run lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run ci-test:unit

      - name: Codecov
        uses: codecov/codecov-action@v2 # https://github.com/codecov/codecov-action

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run build --if-present

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        id: vercel-deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || ''}}

    outputs:
      preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}

  lighthouse:
    name: Run Lighthouse checks
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - name: Lighthouse Check
        id: lighthouse-check
        uses: foo-software/lighthouse-check-action@master # https://github.com/foo-software/lighthouse-check-action
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          urls: https://oppmuntring.sindre.is,${{ needs.deploy.outputs.preview-url }}

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouse-check.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "100"
          minBestPracticesScore: "100"
          minPerformanceScore: "70"
          minProgressiveWebAppScore: "25"
          minSeoScore: "55"

  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - name: Run e2e tests
        run: npm run run-ci-e2e
