name: Pull request

on:
  pull_request:

jobs:
  validate-code:
    name: Validate code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run ci-lint-and-format

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run build --if-present

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - name: Run unit tests
        run: npm run ci-test:unit

      - name: Run e2e tests
        run: npm run run-ci-e2e

      - name: Check code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-unit/lcov.info,coverage-e2e/lcov.info

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      deployments: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          initial-status: in_progress
          environment: Preview

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        id: vercel-deployment
        with:
          github-token: ${{ github.token }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{ steps.vercel-deployment.outputs.preview-url }}
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{ steps.vercel-deployment.outputs.preview-url }}
          state: failure
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

    outputs:
      preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}
